#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("InstantSample.Resource", IsApplication=false)]

namespace InstantSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int dialog_expander_ic_minimized = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public static int dialog_BoolField = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int dialog_Button = 2131034115;
			
			// aapt resource value: 0x7f050009
			public static int dialog_DisclosureField = 2131034121;
			
			// aapt resource value: 0x7f050005
			public static int dialog_ImageLeft = 2131034117;
			
			// aapt resource value: 0x7f050007
			public static int dialog_ImageRight = 2131034119;
			
			// aapt resource value: 0x7f050000
			public static int dialog_LabelField = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int dialog_LabelSubtextField = 2131034113;
			
			// aapt resource value: 0x7f050008
			public static int dialog_Panel = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public static int dialog_RadioButtonList = 2131034122;
			
			// aapt resource value: 0x7f050006
			public static int dialog_SliderField = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public static int dialog_Spinner = 2131034123;
			
			// aapt resource value: 0x7f050004
			public static int dialog_ValueField = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public static int iFormFieldValue = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int separator = 2131034125;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int dialog_labelfieldbelow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int dialog_labelfieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int dialog_onofffieldright = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int dialog_panel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int dialog_root = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int dialog_selectlist = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int dialog_selectlistfield = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int dialog_textarea = 2130903056;
			
			// aapt resource value: 0x7f030011
			public static int dialog_textfieldbelow = 2130903057;
			
			// aapt resource value: 0x7f030012
			public static int dialog_textfieldright = 2130903058;
			
			// aapt resource value: 0x7f030013
			public static int main = 2130903059;
			
			// aapt resource value: 0x7f030014
			public static int sectionedlistseparator = 2130903060;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
